version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    command: /start
    depends_on:
      - postgres
    env_file: .env
    expose:
      - 8000
    image: basic_analytics_prod_django
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    env_file: .env
    image: basic_analytics_prod_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./compose/prod/nginx
    depends_on:
      - django
    image: basic_analytics_prod_nginx
    ports:
      - 80:80
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

volumes:
  media_volume:
  postgres_data:
  static_volume:
